services:
  usuario:
    build:
      context: ./Usuario
      dockerfile: Dockerfile
    ports:
      - "10101:10101"
    env_file:
      - ./Usuario/.env

  disenousuario:
    build:
      context: ./DisenoUsuario
      dockerfile: Dockerfile
    ports:
      - "10102:10102"
    env_file:
      - ./DisenoUsuario/.env

  diseno:
    build:
      context: ./Diseno
      dockerfile: Dockerfile
    ports:
      - "10103:10103"
    env_file:
      - ./Diseno/.env
    
  outfit:
    build:
      context: ./Outfit
      dockerfile: Dockerfile
    ports:
      - "10104:10104"
    env_file:
      - ./Outfit/.env
