services:
  usuario:
    build: 
      context: ./Usuario
      dockerfile: dockerfile
    ports:
      - "10101:10101"
    env_file:
      - ./Usuario/.env

  disenousuario:
    build:
      context: ./DisenoUsuario
      dockerfile: ./dockerfile
    ports:
      - "10102:10102"
    env_file:
      - ./DisenoUsuario/.env
